spring:
  application:
    name: life-hub
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lifehub}
    username: ${DATABASE_USERNAME:lifehub}
    password: ${DATABASE_PASSWORD:lifehub}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:bGlmZWh1Yi1zZWN1cmUtand0LXNlY3JldC1rZXktZm9yLXRva2VuLWdlbmVyYXRpb24tYW5kLXZhbGlkYXRpb24tbXVzdC1iZS1sb25nLWVub3VnaA==}
      expiration: 86400000 # 24 hours
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

notes:
  storage:
    path: ${NOTES_STORAGE_PATH:/app/data}

server:
  port: ${SERVER_PORT:5000}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.lifehub: INFO
    org.springframework.security: DEBUG
